"""
PDF report generator using fpdf2 (pure Python, no heavy deps).
Produces a professional medical report for a completed analysis.
"""
from __future__ import annotations
import json
from datetime import datetime
from pathlib import Path
from fpdf import FPDF, XPos, YPos

from app.services import labels

REPORTS_DIR = Path(__file__).parent.parent.parent / "reports"
REPORTS_DIR.mkdir(exist_ok=True)

# All report text, per language
TEXT = {
    "fr": {
        "subtitle":     "Rapport d'analyse médicale - Document informatif uniquement",
        "footer":       "Ce document est généré automatiquement à titre indicatif. "
                        "Il ne remplace pas un avis médical. Consultez un professionnel de santé.",
        "page":         "Page {n}",
        "patient":      "Informations du patient",
        "name":         "Nom complet",
        "age":          "Âge",
        "age_value":    "{age} ans",
        "sex":          "Sexe",
        "not_set":      "Non renseigné",
        "date":         "Date d'analyse",
        "date_format":  "%d/%m/%Y à %H:%M",
        "ref":          "Réf. analyse",
        "symptoms":     "Symptômes déclarés",
        "duration":     "Durée",
        "severity":     "Sévérité",
        "description":  "Description du patient",
        "urgency":      "Niveau d'urgence",
        "specialist":   "Spécialiste recommandé",
        "predictions":  "Prédictions du modèle IA (Top 5)",
        "headers":      ["#", "Maladie", "Confiance", "Spécialiste"],
        "top_conf":     "Confiance #1 ({disease}) : {pct}",
        "explanation":  "Explication de la prédiction (IA)",
        "contribution": "Contribution de chaque symptôme à la prédiction principale :",
        "warnings":     "Signes d'alerte",
        "disclaimer_title": "Avertissement important",
        "disclaimer":   "Ce rapport est généré par un système d'intelligence artificielle à titre INDICATIF uniquement. "
                        "Les résultats ne constituent pas un diagnostic médical. Consultez obligatoirement un "
                        "professionnel de santé qualifié avant toute décision médicale. En cas d'urgence, "
                        "appelez votre numéro d'urgence local (112 en Europe).",
        "urgency_levels": {"low": "Faible", "moderate": "Modérée", "high": "Élevée", "emergency": "URGENCE"},
        "genders":      {"male": "Homme", "female": "Femme", "other": "Autre"},
        "durations":    {"lt_1d": "Moins d'un jour", "1_3d": "1 à 3 jours", "4_7d": "4 à 7 jours",
                         "1_4w": "1 à 4 semaines", "gt_1m": "Plus d'un mois"},
        "red_flags": {
            "heart_attack":   "Douleur thoracique avec essoufflement, sueurs ou cœur rapide : possible infarctus.",
            "stroke":         "Faiblesse soudaine d'un côté ou troubles de la parole : possibles signes d'AVC.",
            "consciousness":  "Confusion ou baisse de conscience : soins immédiats nécessaires.",
            "meningitis":     "Forte fièvre avec raideur de la nuque : possible méningite.",
            "liver_failure":  "Signes d'insuffisance hépatique aiguë : soins immédiats nécessaires.",
            "bleeding":       "Saignement (selles, vomissements ou crachats) : à faire examiner rapidement.",
            "lung_infection": "Essoufflement avec forte fièvre : possible infection pulmonaire grave.",
            "jaundice":       "Jaunissement de la peau ou des yeux : problème hépatique à évaluer.",
        },
    },
    "en": {
        "subtitle":     "Medical analysis report - For information only",
        "footer":       "This document is generated automatically for information only. "
                        "It does not replace medical advice. Consult a healthcare professional.",
        "page":         "Page {n}",
        "patient":      "Patient information",
        "name":         "Full name",
        "age":          "Age",
        "age_value":    "{age} years",
        "sex":          "Sex",
        "not_set":      "Not provided",
        "date":         "Analysis date",
        "date_format":  "%m/%d/%Y at %H:%M",
        "ref":          "Analysis ref.",
        "symptoms":     "Reported symptoms",
        "duration":     "Duration",
        "severity":     "Severity",
        "description":  "Patient's description",
        "urgency":      "Urgency level",
        "specialist":   "Recommended specialist",
        "predictions":  "AI model predictions (Top 5)",
        "headers":      ["#", "Disease", "Confidence", "Specialist"],
        "top_conf":     "Confidence #1 ({disease}): {pct}",
        "explanation":  "Prediction explanation (AI)",
        "contribution": "Contribution of each symptom to the top prediction:",
        "warnings":     "Warning signs",
        "disclaimer_title": "Important notice",
        "disclaimer":   "This report is generated by an artificial intelligence system for INFORMATION only. "
                        "The results are not a medical diagnosis. Always consult a qualified healthcare "
                        "professional before any medical decision. In an emergency, call your local "
                        "emergency number (112 in Europe).",
        "urgency_levels": {"low": "Low", "moderate": "Moderate", "high": "High", "emergency": "EMERGENCY"},
        "genders":      {"male": "Male", "female": "Female", "other": "Other"},
        "durations":    {"lt_1d": "Less than 1 day", "1_3d": "1-3 days", "4_7d": "4-7 days",
                         "1_4w": "1-4 weeks", "gt_1m": "More than a month"},
        "red_flags": {
            "heart_attack":   "Chest pain with breathlessness, sweating or a racing heart: possible heart attack.",
            "stroke":         "Sudden weakness on one side or slurred speech: possible signs of a stroke.",
            "consciousness":  "Confusion or reduced consciousness: needs immediate medical care.",
            "meningitis":     "High fever with a stiff neck: possible meningitis.",
            "liver_failure":  "Signs of acute liver failure: needs immediate medical care.",
            "bleeding":       "Bleeding (stool, vomit or sputum): should be checked by a doctor promptly.",
            "lung_infection": "Breathlessness with high fever: possible serious lung infection.",
            "jaundice":       "Yellowing of the skin or eyes: liver problem to be assessed.",
        },
    },
}
URGENCY_COLOR = {
    "low":       (39, 174, 96),
    "moderate":  (243, 156, 18),
    "high":      (231, 76, 60),
    "emergency": (192, 57, 43),
}

# ── palette ──────────────────────────────────────────────────────────────────
PRIMARY   = (41, 128, 185)
DARK      = (44, 62, 80)
LIGHT_BG  = (236, 240, 241)
WHITE     = (255, 255, 255)
GRAY      = (127, 140, 141)
SEPARATOR = (189, 195, 199)

# Core fonts (Helvetica) only cover latin-1: map common typographic characters
# to plain ones, anything else becomes "?" instead of crashing the report.
_PLAIN_PUNCTUATION = str.maketrans({
    "–": "-", "—": "-", "‘": "'", "’": "'", "“": '"', "”": '"', "…": "...", "•": "-",
    "œ": "oe", "Œ": "OE", " ": " ",
})


class MedicalPDF(FPDF):
    def __init__(self, patient_name: str, text: dict):
        super().__init__()
        self._patient_name = patient_name
        self._text = text
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(20, 20, 20)

    def normalize_text(self, text):
        text = str(text).translate(_PLAIN_PUNCTUATION)
        return super().normalize_text(text.encode("latin-1", "replace").decode("latin-1"))

    # ── header / footer ──────────────────────────────────────────────────────
    def header(self):
        self.set_fill_color(*PRIMARY)
        self.rect(0, 0, 210, 22, style="F")
        self.set_y(5)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*WHITE)
        self.cell(0, 12, "AI Medical Assistant", align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_font("Helvetica", "", 8)
        self.set_y(14)
        self.cell(0, 6, self._text["subtitle"],
                  align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(*DARK)
        self.ln(6)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(*GRAY)
        self.cell(0, 5, self._text["footer"],
                  align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.cell(0, 5, self._text["page"].format(n=self.page_no()), align="C")

    # ── helpers ───────────────────────────────────────────────────────────────
    def section_title(self, text: str):
        self.ln(4)
        self.set_fill_color(*LIGHT_BG)
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*PRIMARY)
        self.cell(0, 9, f"  {text}", fill=True,
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(*DARK)
        self.ln(2)

    def kv_row(self, label: str, value: str, bold_value: bool = False):
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*GRAY)
        self.cell(55, 7, label + " :", new_x=XPos.RIGHT, new_y=YPos.LAST)
        self.set_font("Helvetica", "B" if bold_value else "", 10)
        self.set_text_color(*DARK)
        self.cell(0, 7, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def thin_line(self):
        self.set_draw_color(*SEPARATOR)
        self.line(20, self.get_y(), 190, self.get_y())
        self.ln(2)


def generate(
    analysis_id: int,
    patient_name: str,
    patient_age: int | None,
    patient_gender: str | None,
    symptoms: list[str],
    symptom_duration: str | None,
    severity: int | None,
    predictions: list[dict],
    urgency_level: str,
    recommended_specialist: str,
    explanation_json: str | None,
    created_at: datetime,
    lang: str = labels.DEFAULT_LANG,
    free_text: str | None = None,
    red_flags: list[dict] | None = None,
    output_path: Path | None = None,
) -> Path:
    """
    Build the PDF in `lang` ("fr" or "en") and return its path on disk.
    predictions = [{"disease": str, "confidence": float, "rank": int, "specialist": str}, ...]
    """
    lang = labels.normalize_lang(lang)
    t = TEXT[lang]
    pdf = MedicalPDF(patient_name, t)
    pdf.add_page()

    # ── 1. Patient info ────────────────────────────────────────────────────
    pdf.section_title(t["patient"])
    pdf.kv_row(t["name"], patient_name)
    pdf.kv_row(t["age"],  t["age_value"].format(age=patient_age) if patient_age else t["not_set"])
    pdf.kv_row(t["sex"],  t["genders"].get(patient_gender, patient_gender.capitalize()) if patient_gender else t["not_set"])
    pdf.kv_row(t["date"], created_at.strftime(t["date_format"]))
    pdf.kv_row(t["ref"],  f"#ANA-{analysis_id:05d}")

    # ── 2. Symptoms ────────────────────────────────────────────────────────
    pdf.section_title(t["symptoms"])
    if symptom_duration:
        pdf.kv_row(t["duration"], t["durations"].get(symptom_duration, symptom_duration))
    if severity:
        pdf.kv_row(t["severity"], f"{severity}/10")
    pdf.ln(1)
    pdf.set_font("Helvetica", "", 10)
    symptom_text = " | ".join(labels.symptom(s, lang) for s in symptoms)
    pdf.set_fill_color(*LIGHT_BG)
    pdf.multi_cell(0, 7, symptom_text, fill=True,
                   new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    if free_text:
        pdf.ln(2)
        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(*GRAY)
        pdf.multi_cell(0, 6, f'{t["description"]} : "{free_text}"',
                       new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(*DARK)

    # ── 3. Urgency ─────────────────────────────────────────────────────────
    pdf.section_title(t["urgency"])
    color = URGENCY_COLOR.get(urgency_level, GRAY)
    label = t["urgency_levels"].get(urgency_level, urgency_level.upper())
    pdf.set_fill_color(*color)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 12, f"  {label}", fill=True,
             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(*DARK)
    pdf.ln(2)
    pdf.kv_row(t["specialist"], labels.specialist(recommended_specialist, lang), bold_value=True)

    # Red flags: symptom combinations that need attention
    if red_flags:
        pdf.ln(2)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(*URGENCY_COLOR["high"])
        pdf.cell(0, 6, t["warnings"], new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_font("Helvetica", "", 9)
        for flag in red_flags:
            message = t["red_flags"].get(flag.get("code"), flag.get("message", ""))
            pdf.multi_cell(0, 5, f"- {message}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.set_text_color(*DARK)

    # ── 4. Predictions ─────────────────────────────────────────────────────
    pdf.section_title(t["predictions"])

    col_w = [8, 80, 42, 40]
    headers = t["headers"]
    pdf.set_fill_color(*PRIMARY)
    pdf.set_text_color(*WHITE)
    pdf.set_font("Helvetica", "B", 9)
    for w, h in zip(col_w, headers):
        pdf.cell(w, 8, h, border=0, fill=True, align="C",
                 new_x=XPos.RIGHT, new_y=YPos.LAST)
    pdf.ln()

    for i, pred in enumerate(predictions[:5]):
        pdf.set_fill_color(*(LIGHT_BG if i % 2 == 0 else WHITE))
        pdf.set_text_color(*DARK)
        pdf.set_font("Helvetica", "B" if i == 0 else "", 9)
        conf_pct = f"{pred['confidence'] * 100:.1f}%"
        cells = [
            (col_w[0], str(pred["rank"])),
            (col_w[1], labels.disease(pred["disease"], lang)),
            (col_w[2], conf_pct),
            (col_w[3], labels.specialist(pred.get("specialist", ""), lang)),
        ]
        for w, val in cells:
            pdf.cell(w, 7, val, fill=True, align="C",
                     new_x=XPos.RIGHT, new_y=YPos.LAST)
        pdf.ln()

    # Confidence bar for rank-1
    if predictions:
        top = predictions[0]
        conf = top["confidence"]
        pdf.ln(4)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 5, t["top_conf"].format(disease=labels.disease(top["disease"], lang), pct=f"{conf*100:.1f}%"),
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        bar_w = int(conf * 150)
        pdf.set_fill_color(*PRIMARY)
        pdf.rect(20, pdf.get_y(), bar_w, 5, style="F")
        pdf.set_fill_color(*LIGHT_BG)
        pdf.rect(20 + bar_w, pdf.get_y(), 150 - bar_w, 5, style="F")
        pdf.ln(8)

    # ── 5. Explanation ─────────────────────────────────────────────────────
    if explanation_json:
        try:
            explanation = json.loads(explanation_json)
            if explanation:
                pdf.section_title(t["explanation"])
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(*GRAY)
                pdf.cell(0, 5,
                         t["contribution"],
                         new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.ln(2)

                max_val = max(abs(v) for v in explanation.values()) or 1
                for sym, score in list(explanation.items())[:8]:
                    label = labels.symptom(sym, lang)
                    bar_len = int(abs(score) / max_val * 80)
                    color = (39, 174, 96) if score >= 0 else (231, 76, 60)
                    sign = "+" if score >= 0 else "-"

                    pdf.set_text_color(*DARK)
                    pdf.set_font("Helvetica", "", 8)
                    pdf.cell(65, 6, label, new_x=XPos.RIGHT, new_y=YPos.LAST)
                    pdf.set_fill_color(*color)
                    pdf.rect(pdf.get_x(), pdf.get_y() + 1, bar_len, 4, style="F")
                    pdf.set_x(pdf.get_x() + bar_len + 2)
                    pdf.set_text_color(*color)
                    pdf.cell(20, 6, f"{sign}{abs(score):.3f}",
                             new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        except (json.JSONDecodeError, ValueError):
            pass

    # ── 6. Disclaimer ──────────────────────────────────────────────────────
    pdf.section_title(t["disclaimer_title"])
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(*GRAY)
    pdf.multi_cell(0, 6, t["disclaimer"], new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Save ───────────────────────────────────────────────────────────────
    path = output_path or REPORTS_DIR / report_filename(analysis_id, lang)
    pdf.output(str(path))
    return path


def report_filename(analysis_id: int, lang: str) -> str:
    """One cached report file per analysis and language."""
    return f"report_ANA{analysis_id:05d}_{labels.normalize_lang(lang)}.pdf"
